title: Wong Hui San
description: |
  ğŸ“ Petaling Jaya, Selangor, Malaysia <br>  
  ğŸ“§ huisan0430@gmail.com <br>  
  ğŸ”— linkedin.com/in/hui-san-wong-844555256/</a> <br>  
theme: jekyll-theme-minimal
