title: Wong Hui San
description: ğŸ“ Location: Petaling Jaya, Malaysia

ğŸ“§ Email: your email address

ğŸ”— LinkedIn: linkedin.com/in/yourname

ğŸ’» GitHub: github.com/yourusername

theme: jekyll-theme-minimal
